---
title: "Cleaning5_Broods_Monthly"
author: "Heywood et al."
output: html_document
editor_options: 
  chunk_output_type: console
---

```{R message = FALSE}
library(tidyverse)
library(readxl)

OUMNH_data_temps<- read_csv('../data/OUMNH_data_temps_Monthly.csv')
NHM_data_temps <- read_csv('../data/NHM_w_temps_Monthly.csv')
BroodTable <- read_csv('../data/brood_table_CTupdates.csv')
```

# Tidying Brood Table

```{r}
Names_table<- read_csv('../data/names_table.csv')

BroodTable %>%
  mutate(FirstMonth = as.numeric(FirstMonthBrood_focal ),
         LastMonth =  as.numeric(LastMonthBrood_focal )) %>%
  filter(Include == 'TRUE' )%>%
  select(`Taxon name` ,  FocalMonthLateLarval , FirstMonth,LastMonth, Univoltine )-> Brood_table2

```

# Adding Brood Tables to NHM
## Now add temperature to use column from   Brood_table_long
```{r}
## Which brood is each record
NHM_data_temps%>%
  left_join(Brood_table2, 
            by = 'Taxon name') %>%
  mutate(InFocalBrood = ifelse(Univoltine, TRUE, 
                               ifelse( between(Month,
                                               FirstMonth,
                                               LastMonth),
                                       TRUE, FALSE))) %>%
  filter( InFocalBrood) %>% 
  filter(!Implausible ) %>%
  mutate( Temp = case_when( FocalMonthLateLarval == 'August'       ~ T_August      ,
                            FocalMonthLateLarval == 'July'         ~ T_July        ,
                            FocalMonthLateLarval == 'June'         ~ T_June        ,  
                            FocalMonthLateLarval == 'May'          ~ T_May         ,
                            FocalMonthLateLarval == 'April'        ~ T_April       ,  
                            FocalMonthLateLarval == 'March'        ~ T_March       ,  
                            FocalMonthLateLarval == 'SeptBefore'   ~ T_SeptBefore  ,  
                            FocalMonthLateLarval == 'AugustBefore' ~ T_AugustBefore,  
                            FocalMonthLateLarval == 'JulyBefore'   ~ T_JulyBefore  ,  
                            FocalMonthLateLarval == 'JuneBefore'   ~ T_JuneBefore  ,  
                            TRUE ~ NA_real_),
          Temp = round(Temp, digits = 3),
          Sex = ifelse( Sex =='N/A', 'undetermined', Sex)  ,
          YearRescale = (Year-1800)/100)%>%
  ### Also filter out erratic Glanville Fritillary observations outside of core population (probably migrants so can't link temperatures)
  filter( `Taxon name` != 'Melitaea cinxia'    |  decimalLongitude < -0.05   )%>%
  select(Sp = `Taxon name`,
         Latitude= decimalLatitude ,
         Longitude= decimalLongitude  ,
         Month, Year ,YearRescale,Sex  , 
         Right_wing=`right_wing (mm)` ,
         FocalMonthLateLarval,
         Temp  ) -> NHM_for_models

write_csv(NHM_for_models, '../data/NHM_for_models_monthly.csv')

```

# Adding Brood Tables and Lats to OUMNH

## Load lats for each location
```{r}
combined_locations <- read_csv("../data/combined_midpoints.csv")
```

## Add all tables including location_midpoints

Also add location filterring

```{r}
OUMNH_for_models <- OUMNH_data_temps %>%
  left_join(combined_locations,
            by = c("Location","LocationType")) %>%
  left_join( select(Brood_table2,
                    `Taxon name`, FirstMonth,LastMonth,
                    Univoltine,
                    FocalMonthLateLarval ),
             by = 'Taxon name') %>%
  mutate(InFocalBrood = ifelse(Univoltine, TRUE, 
                               ifelse( between(Month,
                                               FirstMonth,
                                               LastMonth),
                                       TRUE, FALSE))) %>%
  filter( InFocalBrood) %>% 
  mutate(Temp = case_when(FocalMonthLateLarval == 'August'       ~ T_August      ,
                          FocalMonthLateLarval == 'July'         ~ T_July        ,
                          FocalMonthLateLarval == 'June'         ~ T_June        ,
                          FocalMonthLateLarval == 'May'          ~ T_May         ,
                          FocalMonthLateLarval == 'April'        ~ T_April       ,
                          FocalMonthLateLarval == 'March'        ~ T_March       ,
                          FocalMonthLateLarval == 'SeptBefore'   ~ T_SeptBefore  ,
                          FocalMonthLateLarval == 'AugustBefore' ~ T_AugustBefore,
                          FocalMonthLateLarval == 'JulyBefore'   ~ T_JulyBefore  ,
                          FocalMonthLateLarval == 'JuneBefore'   ~ T_JuneBefore  ,
                          TRUE ~ NA_real_),
         Temp = round(Temp, digits = 3),
         Sex = ifelse( is.na(Sex), 'undetermined', Sex) ,
         YearRescale = (Year-1800)/100) %>%
  filter(between(latitude, 49.5, 54),
         between(longitude, -5.5,4)) %>% ### southerly GB core box (latitude 49.5:54, longitude -5.5:4)
  select(Sp = `Taxon name`,
         Latitude  = latitude,
         Longitude = longitude,
         Month,Year,YearRescale, Sex  , 
         Wing_Length,
         FocalMonthLateLarval,
         Temp  )
## remove 



```

# View and save
```{r}
OUMNH_for_models
write_csv(OUMNH_for_models, "../data/OUMNH_for_models_monthly.csv")
```

