---
title: "Data Distribution"
author: "Chris Terry"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{R}
library(tidyverse)
library(maps)
library(mapdata)    
library(cowplot)

Species_info <- left_join(read_csv('../data/brood_table.csv'),
                          read_csv('../data/names_table.csv'))%>%
  select( Sp = `Taxon name`,
          maximum_plausible,
          minimum_plausible)


NHM_ForFitting <- read_csv(  '../data/NHM_for_models.csv')%>%
  left_join(Species_info)
OUM_ForFitting <- read_csv(  '../data/OUNHM_for_models.csv')

NHM_ForFitting

SouthBritishIsles<- map_data('worldHires') 

```

# Plotting Function

```{r}
Plot_Summary<- function(species, data, dataset, Jitter=FALSE){
  data %>%
    filter(Sp == species)-> XX  ### Only plot out brood 1
  ### 
  if(dataset == 'NHM'){
    XX$Size <- XX$Right_wing
    
    maximum_plausible <- XX$maximum_plausible[1]
    minimum_plausible <- XX$minimum_plausible[1]
  }else{
    XX$Size <- XX$Wing_Length 
    maximum_plausible <- NA
    minimum_plausible <- NA
  }
  
  
  XX%>%
    ggplot()+
    geom_hline( yintercept= maximum_plausible)+
    geom_hline( yintercept= minimum_plausible)+
    geom_point(aes(y = Size, x = Temp, 
                   col = Year, shape = Sex))+
    geom_smooth(method = 'lm', 
                aes(y = Size, x = Temp, group=Sex))+
    
    scale_color_viridis_c(limits = c( 1886,2006) ) -> TempvsSize1
  
  
  if(Jitter){
    XX%>%
      ggplot()+
      geom_polygon(data= SouthBritishIsles,
                   aes(x = long,   y = lat,  group = group, ),
                   fill = 'gray90',  color = 'black')+
      geom_jitter(aes(y = Latitude,  x = Longitude,   col = Year),
                  height = 0.1, width = 0.1, 
                  size = 0.3)+
      scale_color_viridis_c(limits = c( 1886,2006) )+
      coord_fixed(xlim = c(-6, 2) , ylim = c(49.5, 54))+
      theme_minimal()+
      theme(axis.title = element_blank())+
      ggtitle(paste(species, dataset),
              subtitle = 'NB Locations jittered to reduce overlap' )-> Map2
    
  }else{
    XX%>%
      ggplot()+
      geom_polygon(data= SouthBritishIsles,
                   aes(x = long,   y = lat,  group = group, ),
                   fill = 'gray90',  color = 'black')+
      geom_point(aes(y = Latitude,  x = Longitude,   col = Year))+
      scale_color_viridis_c(limits = c( 1886,2006) )+
      coord_fixed(xlim = c(-6, 2) , ylim = c(49.5, 54))+
      theme_minimal()+
      theme(axis.title = element_blank())+
      ggtitle(paste(species, dataset))-> Map2
  }
  
  XX%>%
    ggplot()+
    geom_point(aes(y = Size,x = Latitude, 
                   col = Temp, shape = Sex))+
    #  scale_color_manual(values = c('blue', 'red', 'black')) 
    geom_smooth(method = 'lm', 
                aes(y = Size, x = Latitude))+
    scale_color_viridis_c(limits = c( 4,20), option = 'C' ) -> LatvsSize3
  
    XX%>%
    ggplot()+
    geom_point(aes(y = Size,x = Month))+
    scale_x_continuous(limits=c(1,12))-> MonthSpread
    
    XX%>%
      ggplot(aes(y = Temp ,x = Year ))+
      geom_point()+
      geom_smooth(method = 'lm') -> Temp_year_Corr
    
  plot_grid(Map2+guides(col = 'none', shape = 'none' ),
            TempvsSize1+guides(col = 'none', shape = 'none' ),
            LatvsSize3+guides(col = 'none', shape = 'none' ),
            MonthSpread, 
            Temp_year_Corr,
            nrow=1)-> GroupedFigure
  return(GroupedFigure)
}

###########################################################
## Getting scales
ggplot(NHM_ForFitting)+
  geom_point(aes(y = Right_wing, x = Temp, 
                 col = Year, shape = Sex))+
  scale_color_viridis_c(limits = c( 1886,2006) ) -> TempvsSize1

ggplot(NHM_ForFitting)+
  geom_point(aes(y = Right_wing,x = Latitude,  col = Temp, shape = Sex))+
  scale_color_viridis_c(limits = c( 4,20), option = 'C' ) -> LatvsSize3

Scales <- plot_grid(get_legend(TempvsSize1+guides(col = 'none')),
                    get_legend(TempvsSize1+guides(shape = 'none')),
                    get_legend(LatvsSize3+guides(shape = 'none')),
                    nrow=1)
############################################################


NHM_Species<-sort(unique(NHM_ForFitting$Sp))

plotlist_NHM<-purrr::map(NHM_Species,
                         Plot_Summary,
                         data=NHM_ForFitting, 
                         dataset='NHM' )

## 52 species, 8 per page:
for(i in 1:7){
  plotlist<- plotlist_NHM[ ((i*8)-7):(i*8)]
  EightPlots<- plot_grid( plotlist = plotlist,
                          ncol = 1)
  WithScales<-plot_grid( EightPlots, Scales,
                         rel_heights = c(10,1),
                         ncol = 1)
  
  ## add scales to the bottom of each
  ggsave(paste0('../figs/SI_dataspread_', i ,'.png'), 
         WithScales, width = 8, height = 20, bg = 'white')
}

########
### Weird low temperatures - where are they?


NHM_ForFitting %>%
  filter(Sp == 'Hipparchia semele',
         Brood==1)%>%
  ggplot()+
  geom_polygon(data= SouthBritishIsles,
               aes(x = long,   y = lat,  group = group, ),
               fill = 'gray90',  color = 'black')+
  geom_point(aes(y = Latitude,  x = Longitude,   col = Right_wing>15 ))+
  scale_color_viridis_d( )+
  coord_fixed(xlim = c(-6, 2) , ylim = c(49.5, 54))+
  theme_minimal()+
  theme(axis.title = element_blank())

NHM_filter1%>%
  filter(`Taxon Name`  == 'Hipparchia semele',
         `right_wing (mm)` < 15) %>%
  arrange( `right_wing (mm)` ) %>%
  select(`Taxon Name`,`specimen number`,
         `right_wing (mm)`, year )

## https://data.nhm.ac.uk/object/29e42629-d0c4-45b1-b61a-5a4cf3a3fab5/1748251284062  # Nothing weird about the image. 

```


# OUNHM

```{r}
OUM_Species<-sort(unique(OUM_ForFitting$Sp))

plotlist_OUM<-purrr::map(OUM_Species,
                         Plot_Summary,
                         data=OUM_ForFitting, 
                         dataset='OUM', Jitter = TRUE )


## 8 per page:
for(i in 1:4){
  plotlist_OUM2<- plotlist_OUM[ ((i*8)-7):(i*8)]
  EightPlots<- plot_grid( plotlist = plotlist_OUM2,
                          ncol = 1)
  WithScales<-plot_grid( EightPlots,
                         Scales, ## add scales to the bottom of each
                         rel_heights = c(10,1), ncol = 1)
  
  ggsave(paste0('../figs/SI_OUNHM_dataspread_', i ,'.png'), 
         WithScales, width = 8, height = 20, bg = 'white')
}

```
