---
title: "StatsFitting1_SpeciesLevel"
author: "Chris Terry"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE}
library(tidyverse)
library(brms)
library(posterior)
```

```{r}
NHM_ForFitting <- read_csv(  '../data/NHM_for_models.csv')
OUM_ForFitting <- read_csv(  '../data/OUNHM_for_models.csv')
```

# NHM

## How much data per species/sex/brood?

For now just taking those with at least 100 measurememts. 
```{r}
## Cycle through each species to fit models 

Batches<- count(NHM_ForFitting,
                Sp, Brood ,Sex)%>%
  arrange( n)

## 200 potential models to fit:
Batches$n %>% log10 %>% plot; abline(h = 2) # almost perfect log-normal plot
sum(Batches$n >100) # 154 have over 100, 


### 
Batches %>%
  pivot_wider(values_from = 'n',  names_from = 'Sex', values_fill = 0) %>%
  mutate( Perc_Undetermined = 100* undetermined / ( male+undetermined+female)  ) -> PercentageUndetermined

PercentageUndetermined %>%
  ggplot( aes( x =Perc_Undetermined, fill = Brood))+
  geom_histogram()

NHM_ForFitting%>%
  group_by(Year) %>%
  summarise(FracUndetermined = mean(Sex=='undetermined')) %>%
  ggplot(aes(y= FracUndetermined, x = Year ))+
  geom_point()

### For spotting weirdnesses
NHM_ForFitting %>%
  group_by(Sp, Brood) %>%
  summarise( signif(mean(Year),1), 
             min(Year), 
             quantile(Year, 0.1), 
             quantile(Year, 0.9),
             max(Year), 
             n = n())%>%
  mutate(EightyQuantileRange = `quantile(Year, 0.9)`-`quantile(Year, 0.1)` ) %>%
  arrange( EightyQuantileRange)%>%
  arrange(Sp) -> NHM_Brood_data_spread

# NHM_Brood_data_spread %>%
#   left_join(PercentageUndetermined) %>%
# write_csv('../data/NHM_Brood_data_spread.csv')

```

## Build unique Name for each brood
```{r}
## Exclude all of brood 2:
Batches %>%
  filter(Brood ==1,
         n >100 ) -> TableOfModels_NHM

Set = paste0('Sp.', TableOfModels_NHM$Sp,
             '_Sex.',TableOfModels_NHM$Sex)
```

```{r eval = FALSE}
### Define and compile model
CoreModel <-   NHM_ForFitting %>%
    filter(Sp == TableOfModels_NHM$Sp[1],
           Sex     == TableOfModels_NHM$Sex[1]) %>%
    brm( Right_wing  ~ Year + Temp  + Latitude,
         data = ., refresh = 0)

## Refit model to each set of data, saving each time
for( i in 1:nrow( TableOfModels_NHM)){
  print(Set[i])
  NHM_ForFitting %>%
    filter(Sp == TableOfModels_NHM$Sp[i],
           Sex     == TableOfModels_NHM$Sex[i]) -> batchDATA
  update( CoreModel, newdata = batchDATA, refresh = 0) -> MODEL_FIT
  save(MODEL_FIT, file = paste('../NHM_modelfits3/',Set[i]  ))
}

```

### Collating model outputs into a df

```{r eval = FALSE}
map_df(1:nrow( TableOfModels_NHM), function(i){
  load(file = paste('../NHM_modelfits3/',Set[i]  )) 
  MODEL_FIT %>%
    as_draws_array %>%
    summarise_draws -> Fit_df
  Fit_df$Sp = TableOfModels_NHM$Sp[i]
  Fit_df$Sex = TableOfModels_NHM$Sex[i] 
  return(Fit_df)
})-> Posterior_Summaries_NHM

write_csv(Posterior_Summaries_NHM, '../statsresults/NHM_Posterior_Summaries_dryrun3.csv')

```

# OUNHM

## How much data per species/sex/brood?

For now just taking those with at least 100 measurememts. 
```{r}
## Cycle through each species to fit models 

Batches<- count(OUM_ForFitting,
                Sp, Brood ,Sex)%>%
  arrange( desc(n))

## 200 potential models to fit:
Batches$n  %>% plot; abline(h = 40) # almost perfect log-normal plot
sum(Batches$n  >=40) # 154 have over 40, 

OUM_ForFitting%>%
  group_by(Year) %>%
  summarise(FracUndetermined = mean(Sex=='undetermined')) %>%
  ggplot(aes(y= FracUndetermined, x = Year ))+
  geom_point()

### For spotting weirdnesses
OUM_ForFitting %>%
  group_by(Sp, Brood) %>%
  summarise( signif(mean(Year),1), 
             min(Year), 
             quantile(Year, 0.1), 
             quantile(Year, 0.9),
             max(Year), 
             n = n())%>%
  mutate(EightyQuantileRange = `quantile(Year, 0.9)`-`quantile(Year, 0.1)` ) %>%
  arrange( EightyQuantileRange)%>%
  arrange(Sp) -> OUM_Brood_data_spread

# NHM_Brood_data_spread %>%
#   left_join(PercentageUndetermined) %>%
# write_csv('../data/NHM_Brood_data_spread.csv')

```

## Build unique Name for each brood
```{r}
## Exclude all of brood 2:
Batches %>%
  filter(Brood ==1,
         n >=40 ) -> TableOfModels_OUNHM

Set = paste0('Sp.', TableOfModels_OUNHM$Sp,
             '_Sex.',TableOfModels_OUNHM$Sex)
```

```{r eval = FALSE}
### Define and compile model
CoreModel_OU <-   OUM_ForFitting %>%
    filter(Sp == TableOfModels_OUNHM$Sp[1],
           Sex     == TableOfModels_OUNHM$Sex[1]) %>%
    brm( Wing_Length   ~ Year + Temp  + Latitude,
         data = ., refresh = 0)

## Refit model to each set of data, saving each time
for( i in 1:nrow( TableOfModels_OUNHM)){
  print(Set[i])
  OUM_ForFitting %>%
    filter(Sp == TableOfModels_OUNHM$Sp[i],
           Sex     == TableOfModels_OUNHM$Sex[i]) -> batchDATA
  update( CoreModel_OU, newdata = batchDATA, refresh = 0) -> MODEL_FIT
  save(MODEL_FIT, file = paste('../OUM_modelfits3/',Set[i]  ))
}

```

### Collating model outputs into a df

```{r eval = FALSE}
map_df(1:nrow( TableOfModels_OUNHM), function(i){
  load(file = paste('../OUM_modelfits3/',Set[i]  )) 
  MODEL_FIT %>%
    as_draws_array %>%
    summarise_draws -> Fit_df
  Fit_df$Sp = TableOfModels_OUNHM$Sp[i]
  Fit_df$Sex = TableOfModels_OUNHM$Sex[i] 
  return(Fit_df)
})-> Posterior_Summaries_OUM

write_csv(Posterior_Summaries_OUM, '../statsresults/OUM_Posterior_Summaries_dryrun3.csv')

```


```{R}
sessionInfo()

```