---
title: "StatsFitting3_AcrossSpecies_OUNHMPlus"
author: "Chris Terry"
date: "2025-09-01"
output: html_document
editor_options: 
  chunk_output_type: console
---

Main document for making main text results for the OUNHM data and other comparisons. 

Split off here to be a bit clener and keep the other doc (2) to just be the main NHM results


```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(brms)
library(posterior)
library(forcats)
library(bayesplot)
library(cowplot)
library(ggrepel)
```

```{r}
## Summaries of posteriors of each species-level model
PS_OUM<- read_csv('../statsresults/OUM_Posterior_Summaries_M1.csv')
PS_NHM<- read_csv('../statsresults/NHM_Posterior_Summaries_M1.csv')
```


```{r}
# Specialism 
specialism <- read_csv( '../data/specialism_with_nhm.csv')%>%
  mutate(Label = case_match(Specialism, 
                            'Habitat and foodplant generalist' ~ 'Habitat generalist\n&\nfoodplant generalist',
                            'Habitat and foodplant specialist'~ 'Habitat specialist\n&\nfoodplant specialist',
                            'Habitat generalist and foodplant specialist'~ 'Habitat generalist\n&\nfoodplant specialist',
                            'Habitat specialist and foodplant generalist'~  'Habitat specialist \n&\nfoodplant generalist'))

read_csv('../data/brood_table_CTupdates.csv') %>%
  filter(Include == 'TRUE' )%>%
  select(Sp = `Taxon name` ,Family )-> SpFamily

## Butterfly Red List https://resjournals.onlinelibrary.wiley.com/doi/10.1111/icad.12582
UKRedList <- read_csv('../data/ButterflyRedlistUK.csv')

```


# OUNHM

## Figure for paper main text

```{r}
# ORDER_f3 <- PS_OUM %>%
#   left_join(specialism, by =c( 'Sp'='Taxon name')) %>%
#   distinct(Specialism, Sp ) %>%
#   arrange(Specialism, Sp) %>%pluck('Sp')

PS_OUM %>%
#  mutate(Sp  = factor(Sp, levels = ORDER_f3)) %>% 
  left_join(specialism, by =c( 'Sp'='Taxon name')) %>%
  left_join(SpFamily) %>%
  left_join(UKRedList, by =c( 'Sp'='Species') ) %>%
  filter( variable %in% c( 'b_Temp',
                           'b_YearRescale',
                           'b_Sexmale',
                           'b_Latitude') )%>%
  mutate(Response = case_match(variable, 
                               'b_Temp'~ 'b. Temperature',
                               'b_YearRescale'~'c. Year',
                               'b_Sexmale'~'d. Male Offset',
                               'b_Latitude'~'a. Latitude') )%>%
  ggplot( aes( y =  fct_rev(Sp),
               x = mean))+
  geom_errorbarh(aes( xmin = q5, xmax = q95), linewidth = 1, height = 0, col = 'grey')+
  geom_errorbarh(aes(xmin = q16.7, xmax =  q83.3), linewidth = 2, height = 0, col = 'grey')+
  geom_point(shape = 4)+
  geom_vline(xintercept = 0)+
  facet_grid(~Response, scales = 'free', space = "free_y")+
  theme_bw()+
  theme(  axis.text.y = element_text(face =  "italic"))+
  ylab('')+
  xlab('Fitted Coefficient (OUNHM Dataset)')

##  theme(axis.text.y = element_text(colour = c("gold", "blue", 'darkgreen')))

ggsave('../figs/OUNHM_Monthly_MainSpResults.png', width = 10, height = 5, bg = 'white')
```

## Predictors of b_Temp 

```{r eval = FALSE}
PS_OUM %>%
  left_join(specialism, by =c( 'Sp'='Taxon name')) %>%
  left_join(SpFamily) %>%
  left_join(UKRedList, by =c( 'Sp'='Species') ) %>%
  left_join(SpeciesSizeProps)%>%
  mutate(RedListListed = ifelse(is.na( `GB Red List category`),
                                'Unlisted',
                                'Listed')) %>%
  filter( variable =='b_Temp' )-> bTemp_model_OUM

bTemp_model_OUM %>%
  ggplot(aes( x = MeanRightWing , y =mean     ))+
  geom_point()+
  geom_smooth(method = 'lm')


bTemp_model_OUM %>%
  brm( median|mi(sd)  ~  Specialism,  data = .)%>%
  add_criterion(criterion = c("loo"))-> bTemp_model_OUM

bTemp_model_OUM %>%
  brm( median|mi(sd)  ~  1,  data = .)%>%
  add_criterion(criterion = c("loo")) -> bTemp_model_OUM_NoSpec


bTemp_model_OUM %>%
  brm( median|mi(sd)  ~ RedListListed ,  data = .)%>%
  add_criterion(criterion = c("loo"))-> RedList_bTemp_model_OUM

RedList_bTemp_model_OUM %>% summarise_draws()

save( bTemp_model_OUM, file = '../TopLevelModelFits/bTemp_model_OUM')
save( bTemp_model_OUM_NoSpec, file = '../TopLevelModelFits/bTemp_model_OUM_NoSpec')
save( RedList_bTemp_model_OUM, file = '../TopLevelModelFits/RedList_bTemp_model_OUM')

```

```{r}
load('../TopLevelModelFits/bTemp_model_OUM')
load('../TopLevelModelFits/bTemp_model_OUM_NoSpec')

loo_compare(bTemp_model_OUM,bTemp_model_OUM_NoSpec ) ### It is worth including specialism

bTemp_model_OUM

plot(conditional_effects(bTemp_model_OUM , resp = "median", rug = TRUE), ask = FALSE)
```

## Predictors of b_Year

```{r eval = FALSE}

PS_OUM %>%
  left_join(specialism, by =c( 'Sp'='Taxon name')) %>%
  left_join(SpFamily) %>%
  left_join(UKRedList, by =c( 'Sp'='Species') ) %>%
  left_join(SpeciesSizeProps)%>%
  filter( variable =='b_YearRescale' )-> bYear_model_OUM

bYear_pred_OUM %>%
  brm( median|mi(sd)  ~  Specialism,  data = .)%>%
  add_criterion(criterion = c("loo"))-> bYear_model_OUM

bYear_pred_OUM %>%
  brm( median|mi(sd)  ~  1,  data = .)%>%
  add_criterion(criterion = c("loo")) -> bYear_model_OUM_NoSpec

save( bYear_model_OUM, file = '../TopLevelModelFits/bYear_model_OUM')
save( bYear_model_OUM_NoSpec, file = '../TopLevelModelFits/bYear_model_OUM_NoSpec')
```

```{r}
load('../TopLevelModelFits/bYear_model_OUM')
load('../TopLevelModelFits/bYear_model_OUM_NoSpec')

loo_compare(bYear_model_OUM,
            bYear_model_OUM_NoSpec ) ### It is worth including specialism

bYear_model_OUM

bYear_model_OUM_NoSpec %>% summarise_draws()

plot(conditional_effects(bTemp_model_OUM , resp = "median", rug = TRUE), ask = FALSE)
```

# Comparison to Wilson fits

### Species-level Plots

```{r}
PS_WIL <- read_csv('../statsresults/WIL_Posterior_Summaries_X2.csv')


bind_rows(PS_NHM %>%
            filter( variable %in% c( 'b_Temp',
                                     'b_Latitude',
                                     'b_YearRescale') ) %>%
            mutate( Dataset= 'NHM'), 
          PS_WIL %>%
            filter( variable %in% c( 'b_Wilson_LateTemp',
                                     #    'b_Latitude',
                                     'b_YearRescale') )%>%
            mutate( Dataset= 'Wilson'),
          PS_OUM %>%
            filter( variable %in% c( 'b_Temp',
                                     'b_Latitude',
                                     'b_YearRescale') )%>%
            mutate( Dataset= 'OUNHM')) %>%
  left_join(specialism, by =c( 'Sp'='Taxon name')) -> Joined_coefficients

ORDER <- Joined_coefficients %>%
  filter(variable=='b_Temp', Dataset =='NHM' ) %>%
  arrange(mean) %>%pluck('Sp')


Joined_coefficients%>%
  ggplot( aes( y =  Sp , 
               x = mean, 
               col = Dataset))+
  geom_point()+
  geom_errorbarh(aes( xmin = q5, xmax = q95))+
  geom_vline(xintercept = 0)+
  scale_y_discrete(limits = ORDER)+
  facet_grid(.~variable, scales = 'free')+
  ggtitle('Species-level coefficients')


ggsave(filename = '../figs/compare_coefs_across_three_datasetsM1.png', width = 10, height =6)



Joined_coefficients%>%
  filter(variable%in% c( 'b_Wilson_LateTemp')) %>%
  ggplot( aes( y =  Sp , 
               x = mean, 
               col = Dataset))+
  geom_point()+
  geom_errorbarh(aes( xmin = q5, xmax = q95))+
  geom_vline(xintercept = 0)+
  #scale_y_discrete(limits = ORDER)+
  facet_grid(Specialism~variable, scales = 'free')+
  ggtitle('Species-level coefficients')


## widen dataset to compare coefficents across datasets 

Joined_coefficients %>%
  select(  variable,
           mean, q5, q95, Sp, Dataset, Specialism) %>%
  pivot_wider( id_cols = c('variable', 'Specialism','Sp' ),
               names_from = 'Dataset',
               values_from = c( 'mean','q5','q95' )) %>%
  filter( !is.na(mean_OUNHM )) %>%
  ggplot( aes( y =  mean_NHM , 
               x = mean_OUNHM))+
  geom_point(aes(col = Specialism))+
  geom_errorbarh(aes(col = Specialism,xmin = q5_OUNHM, xmax = q95_OUNHM))+
  geom_errorbar(aes(col = Specialism,ymin = q5_NHM, ymax = q95_NHM))+
  geom_abline(intercept = 0, slope =1)+
  geom_vline(xintercept = 0)+
  geom_hline(yintercept = 0)+
  facet_wrap(~variable, scales = 'free')+
  #coord_fixed()+
  theme(legend.position = 'bottom')+
  ggtitle('Correlation in Species-level coefficients')

ggsave(filename = '../figs/compare_coefs_across_datasets.png', width = 10, height =6)

```

# Session Info

```{r}
sessionInfo()
```
