---
title: "StatsFitting1_SpeciesLevel"
author: "Chris Terry"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE}
library(tidyverse)
library(brms)
library(posterior)
```

```{r}
NHM_ForFitting <- read_csv(  '../data/NHM_for_models_monthly.csv')
OUM_ForFitting <- read_csv(  '../data/OUNHM_for_models_monthly.csv')
```

# NHM Fit with sex as an offset for each species

This allows easier analysis down the line. 

```{r}
## Cycle through each species to fit models 
Batches<- count(NHM_ForFitting,
                Sp)%>%
  arrange( n)

## 200 potential models to fit:
Batches$n %>% log10 %>% plot; abline(h = 2) # almost perfect log-normal plot
sum(Batches$n >100) # 52 species 

```

## Build unique Name for each brood
```{r}
## Exclude all of brood 2:
Batches %>%
  filter( n >100 ) -> TableOfModels_NHM

Set2 = paste0('Sp.', TableOfModels_NHM$Sp)
```

```{r eval = FALSE}
### Define and compile model
CoreModel2 <-   NHM_ForFitting %>%
    filter(Sp == TableOfModels_NHM$Sp[1]) %>%
    brm( log(Right_wing)  ~ YearRescale + Temp  + Latitude + Sex,
         data = ., refresh = 0)

## Refit model to each set of data, saving each time
for( i in 1:nrow( TableOfModels_NHM)){
  print(Set2[i])
  NHM_ForFitting %>%
    filter(Sp == TableOfModels_NHM$Sp[i]) -> batchDATA
  update( CoreModel2, newdata = batchDATA, refresh = 0) -> MODEL_FIT
  save(MODEL_FIT, file = paste('../NHM_modelfitsM1/',Set2[i]  ))
}

```

### Collating model outputs into a df

```{r eval = FALSE}
map_df(1:nrow( TableOfModels_NHM), function(i){
  load(file = paste('../NHM_modelfitsM1/',Set2[i]  )) 
  MODEL_FIT %>%
    as_draws_array %>%
    summarise_draws( "mean","median","sd","mad","quantile2",
                    ~quantile2(.x, probs = c(0.167, 0.833))) -> Fit_df
  Fit_df$Sp = TableOfModels_NHM$Sp[i]
  return(Fit_df)
})-> Posterior_Summaries_NHM2

write_csv(Posterior_Summaries_NHM2, '../statsresults/NHM_Posterior_Summaries_M1.csv')

```

# OUNHM with sex embedded

```{r}
## Cycle through each species to fit models 

Batches<- count(OUM_ForFitting,Sp)%>%
  arrange( desc(n))

Batches$n  %>% plot; abline(h = 40) # almost perfect log-normal plot
sum(Batches$n  >=40) 

```

## Build unique Name for each brood
```{r}
Batches %>%
  filter( n >=40 ) -> TableOfModels_OUNHM

Set2 = paste0('Sp.', TableOfModels_OUNHM$Sp)
```

```{r eval = FALSE}
### Define and compile model when sexes are differentiated 
CoreModel_OU_splitSex <-   OUM_ForFitting %>%
  filter(Sp == TableOfModels_OUNHM$Sp[4]) %>%
  brm( log(Wing_Length)   ~ YearRescale + Temp  + Latitude + Sex,
       data = ., refresh = 0)

CoreModel_OU_jointSex <-   OUM_ForFitting %>%
  filter(Sp == TableOfModels_OUNHM$Sp[2]) %>%
  brm( log(Wing_Length)   ~ YearRescale + Temp  + Latitude ,
       data = ., refresh = 0)

undetermined_sp<- distinct(OUM_ForFitting, Sp, Sex) %>% filter( Sex == 'undetermined') %>% pluck('Sp')

## Refit model to each set of data, saving each time
for( i in 1:nrow( TableOfModels_OUNHM)){
  print(Set2[i])
  if(TableOfModels_OUNHM$Sp[i] %in% undetermined_sp ){
    OUM_ForFitting %>%
      filter(Sp == TableOfModels_OUNHM$Sp[i]) -> batchDATA
    update( CoreModel_OU_jointSex, newdata = batchDATA, refresh = 0) -> MODEL_FIT
    
  }else{
    OUM_ForFitting %>%
      filter(Sp == TableOfModels_OUNHM$Sp[i]) -> batchDATA
    update( CoreModel_OU_splitSex, newdata = batchDATA, refresh = 0) -> MODEL_FIT
  }
  save(MODEL_FIT, file = paste('../OUM_modelfitsM1/',Set2[i]  ))
}
 
 

```

### Collating model outputs into a df

```{r eval = FALSE}
map_df(1:nrow( TableOfModels_OUNHM), function(i){
  load(file = paste('../OUM_modelfitsM1/',Set2[i]  )) 
  MODEL_FIT %>%
    as_draws_array %>%
    summarise_draws("mean","median","sd","mad","quantile2",
                    ~quantile2(.x, probs = c(0.167, 0.833))) -> Fit_df
  Fit_df$Sp = TableOfModels_OUNHM$Sp[i]
  return(Fit_df)
})-> Posterior_Summaries_OUM2

write_csv(Posterior_Summaries_OUM2, '../statsresults/OUM_Posterior_Summaries_M1.csv')

```





















```{R}
sessionInfo()

```