---
title: "StatsFitting4_ Predictor Correlation"
author: "Chris Terry"
date: "2025-09-01"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(brms)
library(posterior)
library(forcats)
library(bayesplot)
library(cowplot)
library(ggrepel)
library(ggcorrplot)
```

```{r}
## Summaries of posteriors of each species-level model
PS_NHM<- read_csv('../statsresults/NHM_Posterior_Summaries_M1.csv')
NHM_ForFitting <- read_csv(  '../data/NHM_for_models_monthly.csv')
```

```{r}
# Specialism 
specialism <- read_csv( '../data/specialism_with_nhm.csv')%>%
  mutate(Label = case_match(Specialism, 
                            'Habitat and foodplant generalist' ~ 'Habitat generalist\n&\nfoodplant generalist',
                            'Habitat and foodplant specialist'~ 'Habitat specialist\n&\nfoodplant specialist',
                            'Habitat generalist and foodplant specialist'~ 'Habitat generalist\n&\nfoodplant specialist',
                            'Habitat specialist and foodplant generalist'~  'Habitat specialist \n&\nfoodplant generalist'))

read_csv('../data/brood_table_CTupdates.csv') %>%
  filter(Include == 'TRUE' )%>%
  select(Sp = `Taxon name` ,Family )-> SpFamily

## Butterfly Red List https://resjournals.onlinelibrary.wiley.com/doi/10.1111/icad.12582
UKRedList <- read_csv('../data/ButterflyRedlistUK.csv')

```

### Prepping data

```{r}
NHM_for_fitting <- read_csv('../data/NHM_for_models_monthly.csv')
NHM_for_fitting %>%
  group_by(Sp)%>%
  summarise(MeanRightWing = signif(mean(Right_wing),4) ,
            SD_RightWing = signif(sd(Right_wing),4),
            CV_RightWing = signif(sd(Right_wing)/mean(Right_wing),4)) -> SpeciesSizeProps

PS_NHM %>%
  left_join(specialism, by =c( 'Sp'='Taxon name')) %>%
  left_join(UKRedList, by =c( 'Sp'='Species') ) %>%
  left_join(SpeciesSizeProps) %>%
  left_join(SpFamily) %>%
  mutate(RedListListed = ifelse(is.na( `GB Red List category`),
                                'Unlisted',
                                'Listed')) %>% 
  filter( variable %in% c( 'b_Temp',
                           'b_YearRescale') )%>%
  mutate(ConfidentTrend =  sign(q5)== sign(q95),
         TrendSign = ifelse(ConfidentTrend, sign(mean), 0)) %>%
  mutate( Generalist = Specialism == 'Habitat and foodplant generalist') %>%
  select(variable,Sp, Specialism , Family, RedListListed , TrendSign, Generalist,
         mean, sd, MeanRightWing,SD_RightWing ,CV_RightWing) -> Trends

```

## Correlations Between Three Predictors

```{R}
Trends %>%
  filter( variable == 'b_Temp') %>%
  mutate( RedListListed = RedListListed== 'Listed') %>%
  select(`Red List` = RedListListed,
         `Average Size` = MeanRightWing,
         Generalist ) %>%
  as.matrix() %>%cor %>%
  ggcorrplot( type = "full",show.diag = FALSE,
               show.legend = FALSE,
              lab = TRUE) -> Predictor_CorrPlot

Predictor_CorrPlot
## Plotting to confirm no size- listing pattern
Trends %>%
  ggplot(aes( x = RedListListed, y = MeanRightWing))+
  geom_boxplot()+
  geom_point()+
  geom_label(aes( label = Sp))+
  scale_y_log10()

Trends %>% 
  filter( variable == 'b_Temp') %>%
  group_by(RedListListed)%>%
  count( Generalist) ->redlist_generalist_table

redlist_generalist_table

redlist_generalist_table%>%
  pluck('n') %>%
  matrix(.,ncol = 2) %>%
  chisq.test()

```

### Distribution of predictors accross families
```{R}
Trends %>%
  filter( variable == 'b_Temp') %>%
  select( Sp, Family, RedListListed, TrendSign, Generalist, MeanRightWing)->x

FamilyCorrelates_a <- ggplot(x, aes( x = Family, fill = RedListListed))+
  geom_bar()+theme_bw()+theme(legend.position="bottom")+
  scale_fill_manual(values = c('darkred', 'lightgreen'))+
  ylab('Count in Dataset')

FamilyCorrelates_b <- ggplot(x, aes( x = Family, y = MeanRightWing))+
  geom_boxplot()+geom_point()+theme_bw()+theme(legend.position="bottom")+
  ylab('Average Size')

FamilyCorrelates_c <- ggplot(x, aes( x = Family, fill = Generalist))+
  geom_bar()+theme_bw()+theme(legend.position="bottom")+
  scale_fill_manual(values = c('blue','yellow' ))+
  ylab('Count in Dataset')


plot_grid( FamilyCorrelates_a,
           FamilyCorrelates_b,
           FamilyCorrelates_c, ncol = 3) 
```

### Making SI Correlation plot

```{r}
plot_grid(Predictor_CorrPlot,
          FamilyCorrelates_a,
          FamilyCorrelates_b,
          FamilyCorrelates_c, 
          labels = c('a) Correlations',
                     'b) Red Listing by Family', 
                     'c) Average Size by Family',
                     'd) Specialism by Family'),
          scale = 0.85  , hjust =0)
          
ggsave('../figs/SI_correlation_in_predictors.png',
       width = 12, height = 6, bg = 'white')

```


# Session Info

```{r}
sessionInfo()
```