---
title: "Data Distribution"
author: "Chris Terry"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This document visualises the spatio-temporal distribution of records used for each of the datasets. 

```{R}
library(tidyverse)
library(maps)
library(mapdata)    
library(cowplot)

Species_info <- left_join(read_csv('../data/brood_table.csv'),
                          read_csv('../data/names_table.csv'))%>%
  select( Sp = `Taxon name`,
          maximum_plausible,
          minimum_plausible)


NHM_ForFitting <- read_csv(  '../data/NHM_for_models_monthly.csv')%>%
  left_join(Species_info)
OUM_ForFitting <- read_csv(  '../data/OUMNH_for_models_monthly.csv')


SouthBritishIsles<- map_data('worldHires') 
```

# Plotting Function

```{r}
Plot_Summary<- function(species, data, dataset, Jitter=FALSE){
  data %>%
    filter(Sp == species)-> XX 
  
  if(dataset == 'NHM'){XX$Size <- XX$Right_wing
  }else{ XX$Size <- XX$Wing_Length }

  
  if(dataset == 'NHM'){
    maximum_plausible <- XX$maximum_plausible[1]
    minimum_plausible <- XX$minimum_plausible[1]
    
    TempvsSize1 <-  TempvsSize1+
      geom_hline( yintercept= maximum_plausible)+
      geom_hline( yintercept= minimum_plausible)
  }
  
  if(Jitter){
    XX%>%
      ggplot()+
      geom_polygon(data= SouthBritishIsles,
                   aes(x = long,   y = lat,  group = group, ),
                   fill = 'gray90',  color = 'black')+
      geom_jitter(aes(y = Latitude,  x = Longitude,   col = Year),
                  height = 0.1, width = 0.1, 
                  size = 0.3)+
      scale_color_viridis_c(limits = c( 1880,2020) )+
      coord_fixed(xlim = c(-6, 2) , ylim = c(49.5, 54))+
      theme_minimal()+
      theme(axis.title = element_blank())+
      ggtitle(paste0(species,' (',dataset,')'))-> Map2
    
  }else{
    XX%>%
      ggplot()+
      geom_polygon(data= SouthBritishIsles,
                   aes(x = long,   y = lat,  group = group, ),
                   fill = 'gray90',  color = 'black')+
      geom_point(aes(y = Latitude,  x = Longitude,   col = Year))+
      scale_color_viridis_c(limits = c( 1880,2020) )+
      coord_fixed(xlim = c(-6, 2) , ylim = c(49.5, 54))+
      theme_minimal()+
      theme(axis.title = element_blank())+
      ggtitle(paste(species ))-> Map2
  }
  
  XX%>%
    ggplot()+
    geom_point(aes(y = Size, x = Temp, 
                   col = Year, shape = Sex))+
    geom_smooth(method = 'lm', 
                aes(y = Size, x = Temp))+
    xlab('Temperature')+
    theme_bw()+
    scale_color_viridis_c(limits = c( 1880,2020) ) -> TempvsSize1
  
  XX%>%
    ggplot()+
    geom_point(aes(y = Size,x = Latitude, 
                   col = Temp, shape = Sex))+
    #  scale_color_manual(values = c('blue', 'red', 'black')) 
    geom_smooth(method = 'lm', 
                aes(y = Size, x = Latitude))+
    scale_x_continuous(limits =  c(49.5, 54))+
    theme_bw()+
    scale_color_viridis_c(limits = c( 4,20), option = 'C' ) -> LatvsSize3
  
  # XX%>%
  #   ggplot()+
  #   geom_point(aes(y = Size,x = Month))+
  #   scale_x_continuous(limits=c(2,12), breaks = c(2:12))-> MonthSpread
   
  XX%>%
    ggplot(aes(y = Size ,x = Year ))+
    geom_point()+
    scale_x_continuous(limits =  c( 1880,2020) )+
    theme_bw()+
    geom_smooth(method = 'lm') -> Size_Year_Corr
  
  XX%>%
    ggplot(aes(y = Temp ,x = Year ))+
    geom_point()+
    scale_x_continuous(limits =  c( 1880,2020) )+
    ylab('Temperature')+
    theme_bw()+
    geom_smooth(method = 'lm') -> Temp_year_Corr
  
  plot_grid(Map2+guides(col = 'none', shape = 'none' ),
            TempvsSize1+guides(col = 'none', shape = 'none', linetype='none' ),
            LatvsSize3+guides(col = 'none', shape = 'none' ),
            #MonthSpread, 
            Size_Year_Corr,
            Temp_year_Corr,
            rel_widths = c( 2,1,1,1,1),
            nrow=1)-> GroupedFigure
  return(GroupedFigure)
}

###########################################################
## Getting scales
ggplot(NHM_ForFitting)+
  geom_point(aes(y = Right_wing, x = Temp, 
                 col = Year, shape = Sex))+
  scale_color_viridis_c(limits = c( 1880,2020) ) -> TempvsSize1

ggplot(NHM_ForFitting)+
  geom_point(aes(y = Right_wing,x = Latitude,  col = Temp, shape = Sex))+
  scale_color_viridis_c(limits = c( 4,20), option = 'C' ) -> LatvsSize3

Scales <- plot_grid(get_legend(TempvsSize1+guides(col = 'none')),
                    get_legend(TempvsSize1+guides(shape = 'none')),
                    get_legend(LatvsSize3+guides(shape = 'none')),
                    nrow=1)
############################################################
```

# Making NHM Maps and Plots

```{r eval = FALSE}

NHM_Species<-sort(unique(NHM_ForFitting$Sp))

plotlist_NHM<-purrr::map(NHM_Species,
                         Plot_Summary,
                         data=NHM_ForFitting, 
                         dataset='NHM' )

## 52 species, 7 per page, 8 pages
for(i in 1:8){
  plotlist<- plotlist_NHM[((i*7)-6):(i*7)]

  if( i == 8){
    ## add scales to the bottom of last one
    
      ThreePlots<- plot_grid( plotlist = plotlist[1:3],
                          ncol = 1)
        WithScales<-plot_grid( ThreePlots, Scales,
                           rel_heights = c(4,1),
                           ncol = 1)
    ggsave(paste0('../figs/SI_NHM_dataspread_', i ,'.png'), 
           WithScales, width = 8, height = 8, bg = 'white')
  }else{
     SevenPlots<- plot_grid( plotlist = plotlist,
                          ncol = 1)
    ggsave(paste0('../figs/SI_NHM_dataspread_', i ,'.png'), 
           SevenPlots, width = 8, height = 12, bg = 'white')
  }
}


```

# OUMNH Maps and Plots

```{r eval = FALSE}
OUM_Species<-sort(unique(OUM_ForFitting$Sp))

plotlist_OUM<-purrr::map(OUM_Species,
                         Plot_Summary,
                         data=OUM_ForFitting, 
                         dataset='OUM', Jitter = TRUE )


## 7 per page:
for(i in 1:4){
  plotlist_OUM2<- plotlist_OUM[ ((i*7)-6):(i*7)]
  
  if(i == 4){
  Plots<- plot_grid( plotlist = plotlist_OUM2,
                          ncol = 1)
  WithScales<-plot_grid( Plots,
                         Scales, ## add scales to the bottom of each
                         rel_heights = c(10,1), ncol = 1)
  
  ggsave(paste0('../figs/SI_OUM_dataspread_', i ,'.png'), 
         WithScales, width = 8, height = 12, bg = 'white')
  }else{
      Plots<- plot_grid( plotlist = plotlist_OUM2,
                          ncol = 1)
  ggsave(paste0('../figs/SI_OUM_dataspread_', i ,'.png'), 
         Plots, width = 8, height = 14, bg = 'white')
  }
}

```
